# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Dr Alice Violett"

# A description of your site for meta tag, search engine results.
description: "Book thoughts and PhD-related posts"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://www.draliceviolett.com"

# Favicon
favicon: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Blog
    url: /
  - text: About my PhD
    url: /phd-blog/
  - text: About me
    url: /about/

# The shortname for your Disqus site to enable comments.

# Colors
accent_color: '#2a456b'

# Site footer
footer:
  content: "&copy; Scriptor all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

include: [_redirects]